project:
  type: book
  output-dir: _book

book:
  title: "Spectral Finite Element Methods"
  author: "Vikas Sharma"
  date: "1/24/2025"
  reader-mode: true
  search: true
  repo-url: https://github.com/poromechanics/spectral-fem/
  repo-actions: [edit, issue]
  downloads: [pdf,epub]
  sharing: [twitter, linkedin]
  favicon: ./figures/favicon.png
  cover-image: ./figures/cover.svg
  cover-image-alt: Spectral FEM
  twitter-card: true
  site-url: https://vikas.easifem.com
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Vikas Sharma" 
    right: 
      - icon: github
        href: https://github.com/vickysharma0812
      - icon: twitter
        href: https://twitter.com/vickysharma0812
      - icon: linkedin
        href: https://linkedin.com/in/vickysharma0812
  sidebar:
      style: docked
      background: light
  chapters:
    - index.md
    - intro.md
    - part: "Fourier Spectral Methods"
      chapters:
        - ./fourier-expansion.md
        - ./fourier-galerkin-method.md
        - ./fourier-collocation-method.md
    - part: "Orthogonal polynomial"
      chapters: 
        - ./orthogonal-polynomials.md
        - ./jacobi-polynomials.md
        - ./ultraspherical-polynomials.md
        - ./legendre-polynomials.md
        - ./chebyshev-polynomials.md
        - ./lobatto-polynomials.md
    - part: "Orthogonal polynomial expansion"
      chapters: 
        - ./orthogonal-polynomial-expansion.md
        - ./jacobi-polynomial-expansion.md
        - ./ultraspherical-polynomial-expansion.md
        - ./legendre-polynomial-expansion.md
        - ./chebyshev-polynomial-expansion.md
    - summary.md
    - references.md

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



